version: "3"
services:
    db:
      build: ./db
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
      restart: always
    web:
      build: ./web
      environment:
        mysql_host: ${mysql_host}
        mysql_user: ${mysql_user}
        mysql_password: ${mysql_password}
        mysql_database: ${mysql_database}
      ports:
        - ${localport}:${containerport}
      depends_on:
        - db
      restart: on-failure