#This container relies on the multi-stage method to make it easy to compile and run the code easliy


# Step 1: Compile TS to JS
FROM node:latest as step1
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Step 2: Remove TS
FROM node:latest as step2
WORKDIR /app
COPY --from=step1 /app/package.json .
COPY --from=step1 /app/build .
RUN npm install --only=production

# Step 3: Distroless Container
FROM  gcr.io/distroless/nodejs:latest
WORKDIR /app
COPY --from=step2 /app .
EXPOSE 8000
CMD ["server.js"]